### ISSUE TITLE
HTTPS Certificate Broken

### ISSUE THREAD

**Issue by ericjiang97** [sph-huynh/sophee#1]
See Image below:
![image](https://user-images.githubusercontent.com/5687681/38179105-6cb9aae8-3662-11e8-99b4-7a485f5eb04d.png)

Maybe update cert? Or maybe even use a CDN provided Cert?

**Comment by sph-huynh** [comment]
Hello yes I was not expecting anybody to see my repository so soon 🤣  . It was broken because the website hadn't been deployed yet - it should be good now.
